// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "button.np.hxx"

Rpc::Button::Button(std::optional<uint32_t> tag, std::string text,
                    uint32_t on_click)
    : Widget(tag), text(std::move(text)), on_click(on_click) {}

size_t Rpc::Button::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 16;

  if (reader.read_field_size(0) < 0) {
    tag = std::nullopt;
  } else {
    uint32_t tag_value;
    reader.read_uint32(ptr, tag_value);
    tag = tag_value;
    ptr += 4;
  }

  const int32_t text_size = reader.read_field_size(1);
  reader.read_string(ptr, text_size, text);
  ptr += text_size;

  reader.read_uint32(ptr, on_click);
  ptr += 4;

  return ptr;
}

NanoPack::TypeId Rpc::Button::type_id() const { return TYPE_ID; }

size_t Rpc::Button::header_size() const { return 16; }

size_t Rpc::Button::write_to(NanoPack::Writer &writer, int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(16);

  writer.write_type_id(TYPE_ID, offset);

  if (tag.has_value()) {
    writer.write_field_size(0, 4, offset);
    writer.append_uint32(*tag);
  } else {
    writer.write_field_size(0, -1, offset);
  }

  writer.write_field_size(1, text.size(), offset);
  writer.append_string(text);

  writer.write_field_size(2, 4, offset);
  writer.append_uint32(on_click);

  return writer.size() - writer_size_before;
}
