// AUTOMATICALLY GENERATED BY NANOC

#ifndef BUTTON_NP_HXX
#define BUTTON_NP_HXX
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <string>

#include "make_widget.np.hxx"
#include "widget.np.hxx"

namespace Rpc {

struct Button : Widget {
  static constexpr NanoPack::TypeId TYPE_ID = 320412644;

  std::string text;
  uint32_t on_click;

  Button() = default;

  Button(std::optional<uint32_t> tag, std::string text, uint32_t on_click);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
