// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "center.np.hxx"

Rpc::Center::Center(std::optional<uint32_t> tag, std::unique_ptr<Widget> child)
    : Widget(tag), child(std::move(child)) {}

size_t Rpc::Center::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 12;

  if (reader.read_field_size(0) < 0) {
    tag = std::nullopt;
  } else {
    uint32_t tag_value;
    reader.read_uint32(ptr, tag_value);
    tag = tag_value;
    ptr += 4;
  }

  size_t child_bytes_read;
  reader.buffer += ptr;
  child = std::move(make_widget(reader, child_bytes_read));
  reader.buffer = buf;
  ptr += child_bytes_read;

  return ptr;
}

Rpc::Widget &Rpc::Center::get_child() const { return *child; }

NanoPack::TypeId Rpc::Center::type_id() const { return TYPE_ID; }

size_t Rpc::Center::header_size() const { return 12; }

size_t Rpc::Center::write_to(NanoPack::Writer &writer, int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(12);

  writer.write_type_id(TYPE_ID, offset);

  if (tag.has_value()) {
    writer.write_field_size(0, 4, offset);
    writer.append_uint32(*tag);
  } else {
    writer.write_field_size(0, -1, offset);
  }

  const size_t child_byte_size = child->write_to(writer, writer.size());
  writer.write_field_size(1, child_byte_size, offset);

  return writer.size() - writer_size_before;
}
