// AUTOMATICALLY GENERATED BY NANOC

#ifndef CENTER_NP_HXX
#define CENTER_NP_HXX
#include <memory>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>

#include "make_widget.np.hxx"
#include "widget.np.hxx"

namespace Rpc {

struct Center : Widget {
  static constexpr NanoPack::TypeId TYPE_ID = 1855640887;

  std::unique_ptr<Widget> child;

  Center() = default;

  Center(std::optional<uint32_t> tag, std::unique_ptr<Widget> child);

  size_t read_from(NanoPack::Reader &reader);

  [[nodiscard]] Widget &get_child() const;

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
