// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "column.np.hxx"

Rpc::Column::Column(std::optional<uint32_t> tag, double width, double height,
                    const Alignment &horizontal_alignment,
                    const Alignment &vertical_alignment,
                    std::vector<std::unique_ptr<Widget>> children)
    : Widget(tag), width(width), height(height),
      horizontal_alignment(horizontal_alignment),
      vertical_alignment(vertical_alignment), children(std::move(children)) {}

size_t Rpc::Column::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 28;

  if (reader.read_field_size(0) < 0) {
    tag = std::nullopt;
  } else {
    uint32_t tag_value;
    reader.read_uint32(ptr, tag_value);
    tag = tag_value;
    ptr += 4;
  }

  reader.read_double(ptr, width);
  ptr += 8;

  reader.read_double(ptr, height);
  ptr += 8;

  int8_t horizontal_alignment_raw_value;
  reader.read_int8(ptr, horizontal_alignment_raw_value);
  ptr += 1;
  horizontal_alignment = Alignment(horizontal_alignment_raw_value);

  int8_t vertical_alignment_raw_value;
  reader.read_int8(ptr, vertical_alignment_raw_value);
  ptr += 1;
  vertical_alignment = Alignment(vertical_alignment_raw_value);

  int32_t children_vec_size;
  reader.read_int32(ptr, children_vec_size);
  ptr += 4;
  children.resize(children_vec_size);
  for (int i = 0; i < children_vec_size; ++i) {
    auto &i_item = children[i];
    size_t i_item_bytes_read;
    reader.buffer += ptr;
    i_item = std::move(make_widget(reader, i_item_bytes_read));
    reader.buffer = buf;
    ptr += i_item_bytes_read;
  }

  return ptr;
}

NanoPack::TypeId Rpc::Column::type_id() const { return TYPE_ID; }

size_t Rpc::Column::header_size() const { return 28; }

size_t Rpc::Column::write_to(NanoPack::Writer &writer, int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(28);

  writer.write_type_id(TYPE_ID, offset);

  if (tag.has_value()) {
    writer.write_field_size(0, 4, offset);
    writer.append_uint32(*tag);
  } else {
    writer.write_field_size(0, -1, offset);
  }

  writer.write_field_size(1, 8, offset);
  writer.append_double(width);

  writer.write_field_size(2, 8, offset);
  writer.append_double(height);

  writer.write_field_size(3, 1, offset);
  writer.append_int8(horizontal_alignment.value());

  writer.write_field_size(4, 1, offset);
  writer.append_int8(vertical_alignment.value());

  const size_t children_vec_size = children.size();
  writer.append_int32(children_vec_size);
  int32_t children_byte_size = sizeof(int32_t);
  for (auto &i : children) {
    const size_t i_byte_size = i->write_to(writer, writer.size());
    children_byte_size += i_byte_size;
  }
  writer.write_field_size(5, children_byte_size, offset);

  return writer.size() - writer_size_before;
}
