// AUTOMATICALLY GENERATED BY NANOC

#ifndef FONT_STYLE_NP_HXX
#define FONT_STYLE_NP_HXX
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <string>

namespace Rpc {

struct FontStyle : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 3635009167;

  std::string font_family;
  uint32_t font_weight;
  uint32_t font_size;

  FontStyle() = default;

  FontStyle(std::string font_family, uint32_t font_weight, uint32_t font_size);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
