// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "font_style.np.hxx"

Rpc::FontStyle::FontStyle(std::string font_family, uint32_t font_weight,
                          uint32_t font_size)
    : font_family(std::move(font_family)), font_weight(font_weight),
      font_size(font_size) {}

size_t Rpc::FontStyle::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 16;

  const int32_t font_family_size = reader.read_field_size(0);
  reader.read_string(ptr, font_family_size, font_family);
  ptr += font_family_size;

  reader.read_uint32(ptr, font_weight);
  ptr += 4;

  reader.read_uint32(ptr, font_size);
  ptr += 4;

  return ptr;
}

NanoPack::TypeId Rpc::FontStyle::type_id() const { return TYPE_ID; }

size_t Rpc::FontStyle::header_size() const { return 16; }

size_t Rpc::FontStyle::write_to(NanoPack::Writer &writer, int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(16);

  writer.write_type_id(TYPE_ID, offset);

  writer.write_field_size(0, font_family.size(), offset);
  writer.append_string(font_family);

  writer.write_field_size(1, 4, offset);
  writer.append_uint32(font_weight);

  writer.write_field_size(2, 4, offset);
  writer.append_uint32(font_size);

  return writer.size() - writer_size_before;
}
