// AUTOMATICALLY GENERATED BY NANOC

#ifndef LIST_VIEW_DELETE_OPERATION_NP_HXX
#define LIST_VIEW_DELETE_OPERATION_NP_HXX
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <vector>

#include "list_view_operation.np.hxx"
#include "make_list_view_operation.np.hxx"

namespace Rpc {

struct ListViewDeleteOperation : ListViewOperation {
  static constexpr NanoPack::TypeId TYPE_ID = 2223513129;

  std::vector<int32_t> delete_at;

  ListViewDeleteOperation() = default;

  ListViewDeleteOperation(uint32_t tag, std::vector<int32_t> delete_at);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
