// AUTOMATICALLY GENERATED BY NANOC

#ifndef LIST_VIEW_ITEM_CONFIG_NP_HXX
#define LIST_VIEW_ITEM_CONFIG_NP_HXX
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <optional>

namespace Rpc {

struct ListViewItemConfig : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 4128951807;

  std::optional<uint32_t> section_index;
  std::optional<uint32_t> item_index;
  std::optional<uint32_t> item_tag;

  ListViewItemConfig() = default;

  ListViewItemConfig(std::optional<uint32_t> section_index,
                     std::optional<uint32_t> item_index,
                     std::optional<uint32_t> item_tag);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
