// AUTOMATICALLY GENERATED BY NANOC

#ifndef LIST_VIEW_ITEM_NP_HXX
#define LIST_VIEW_ITEM_NP_HXX
#include <memory>
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>

#include "make_widget.np.hxx"
#include "widget.np.hxx"

namespace Rpc {

struct ListViewItem : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 1100735111;

  uint32_t item_tag;
  std::unique_ptr<Widget> widget;

  ListViewItem() = default;

  ListViewItem(uint32_t item_tag, std::unique_ptr<Widget> widget);

  size_t read_from(NanoPack::Reader &reader);

  [[nodiscard]] Widget &get_widget() const;

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
