// AUTOMATICALLY GENERATED BY NANOC

#ifndef LIST_VIEW_NP_HXX
#define LIST_VIEW_NP_HXX
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <vector>

#include "make_widget.np.hxx"
#include "widget.np.hxx"

namespace Rpc {

struct ListView : Widget {
  static constexpr NanoPack::TypeId TYPE_ID = 2164488861;

  double width;
  double height;
  std::vector<uint32_t> sections;
  double item_height;
  uint32_t on_create;
  uint32_t on_bind;

  ListView() = default;

  ListView(std::optional<uint32_t> tag, double width, double height,
           std::vector<uint32_t> sections, double item_height,
           uint32_t on_create, uint32_t on_bind);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
