// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "list_view_operation.np.hxx"

Rpc::ListViewOperation::ListViewOperation(uint32_t tag) : tag(tag) {}

size_t Rpc::ListViewOperation::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 8;

  reader.read_uint32(ptr, tag);
  ptr += 4;

  return ptr;
}

NanoPack::TypeId Rpc::ListViewOperation::type_id() const { return TYPE_ID; }

size_t Rpc::ListViewOperation::header_size() const { return 8; }

size_t Rpc::ListViewOperation::write_to(NanoPack::Writer &writer,
                                        int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(8);

  writer.write_type_id(TYPE_ID, offset);

  writer.write_field_size(0, 4, offset);
  writer.append_uint32(tag);

  return writer.size() - writer_size_before;
}
