// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "list_view.np.hxx"

Rpc::ListView::ListView(std::optional<uint32_t> tag, double width,
                        double height, std::vector<uint32_t> sections,
                        double item_height, uint32_t on_create,
                        uint32_t on_bind)
    : Widget(tag), width(width), height(height), sections(std::move(sections)),
      item_height(item_height), on_create(on_create), on_bind(on_bind) {}

size_t Rpc::ListView::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 32;

  if (reader.read_field_size(0) < 0) {
    tag = std::nullopt;
  } else {
    uint32_t tag_value;
    reader.read_uint32(ptr, tag_value);
    tag = tag_value;
    ptr += 4;
  }

  reader.read_double(ptr, width);
  ptr += 8;

  reader.read_double(ptr, height);
  ptr += 8;

  const int32_t sections_byte_size = reader.read_field_size(3);
  const int32_t sections_vec_size = sections_byte_size / 4;
  sections.resize(sections_vec_size);
  for (int i = 0; i < sections_vec_size; ++i) {
    auto &i_item = sections[i];
    reader.read_uint32(ptr, i_item);
    ptr += 4;
  }

  reader.read_double(ptr, item_height);
  ptr += 8;

  reader.read_uint32(ptr, on_create);
  ptr += 4;

  reader.read_uint32(ptr, on_bind);
  ptr += 4;

  return ptr;
}

NanoPack::TypeId Rpc::ListView::type_id() const { return TYPE_ID; }

size_t Rpc::ListView::header_size() const { return 32; }

size_t Rpc::ListView::write_to(NanoPack::Writer &writer, int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(32);

  writer.write_type_id(TYPE_ID, offset);

  if (tag.has_value()) {
    writer.write_field_size(0, 4, offset);
    writer.append_uint32(*tag);
  } else {
    writer.write_field_size(0, -1, offset);
  }

  writer.write_field_size(1, 8, offset);
  writer.append_double(width);

  writer.write_field_size(2, 8, offset);
  writer.append_double(height);

  const int32_t sections_byte_size = sections.size() * 4;
  writer.write_field_size(3, sections_byte_size, offset);
  for (const auto &i : sections) {
    writer.append_uint32(i);
  }

  writer.write_field_size(4, 8, offset);
  writer.append_double(item_height);

  writer.write_field_size(5, 4, offset);
  writer.append_uint32(on_create);

  writer.write_field_size(6, 4, offset);
  writer.append_uint32(on_bind);

  return writer.size() - writer_size_before;
}
