// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "list_view_item.np.hxx"

Rpc::ListViewItem::ListViewItem(uint32_t item_tag,
                                std::unique_ptr<Widget> widget)
    : item_tag(item_tag), widget(std::move(widget)) {}

size_t Rpc::ListViewItem::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 12;

  reader.read_uint32(ptr, item_tag);
  ptr += 4;

  size_t widget_bytes_read;
  reader.buffer += ptr;
  widget = std::move(make_widget(reader, widget_bytes_read));
  reader.buffer = buf;
  ptr += widget_bytes_read;

  return ptr;
}

Rpc::Widget &Rpc::ListViewItem::get_widget() const { return *widget; }

NanoPack::TypeId Rpc::ListViewItem::type_id() const { return TYPE_ID; }

size_t Rpc::ListViewItem::header_size() const { return 12; }

size_t Rpc::ListViewItem::write_to(NanoPack::Writer &writer, int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(12);

  writer.write_type_id(TYPE_ID, offset);

  writer.write_field_size(0, 4, offset);
  writer.append_uint32(item_tag);

  const size_t widget_byte_size = widget->write_to(writer, writer.size());
  writer.write_field_size(1, widget_byte_size, offset);

  return writer.size() - writer_size_before;
}
