// AUTOMATICALLY GENERATED BY NANOC

#ifndef LIST_VIEW_BATCH_OPERATIONS_NP_HXX
#define LIST_VIEW_BATCH_OPERATIONS_NP_HXX
#include <memory>
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <vector>

#include "list_view_operation.np.hxx"
#include "make_list_view_operation.np.hxx"

namespace Rpc {

struct ListViewBatchOperations : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 3604546751;

  std::vector<std::unique_ptr<ListViewOperation>> operations;

  ListViewBatchOperations() = default;

  explicit ListViewBatchOperations(
      std::vector<std::unique_ptr<ListViewOperation>> operations);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
