// AUTOMATICALLY GENERATED BY NANOC

#ifndef LIST_VIEW_OPERATION_NP_HXX
#define LIST_VIEW_OPERATION_NP_HXX
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>

namespace Rpc {

struct ListViewOperation : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 3516816492;

  uint32_t tag;

  ListViewOperation() = default;

  explicit ListViewOperation(uint32_t tag);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
