// AUTOMATICALLY GENERATED BY NANOC

#ifndef LIST_VIEW_INSERT_OPERATION_NP_HXX
#define LIST_VIEW_INSERT_OPERATION_NP_HXX
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <vector>

#include "list_view_operation.np.hxx"
#include "make_list_view_operation.np.hxx"

namespace Rpc {

struct ListViewInsertOperation : ListViewOperation {
  static constexpr NanoPack::TypeId TYPE_ID = 2077451345;

  std::vector<int32_t> insert_at;

  ListViewInsertOperation() = default;

  ListViewInsertOperation(uint32_t tag, std::vector<int32_t> insert_at);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
