// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "list_view_batch_operations.np.hxx"

Rpc::ListViewBatchOperations::ListViewBatchOperations(
    std::vector<std::unique_ptr<ListViewOperation>> operations)
    : operations(std::move(operations)) {}

size_t Rpc::ListViewBatchOperations::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 8;

  int32_t operations_vec_size;
  reader.read_int32(ptr, operations_vec_size);
  ptr += 4;
  operations.resize(operations_vec_size);
  for (int i = 0; i < operations_vec_size; ++i) {
    auto &i_item = operations[i];
    size_t i_item_bytes_read;
    reader.buffer += ptr;
    i_item = std::move(make_list_view_operation(reader, i_item_bytes_read));
    reader.buffer = buf;
    ptr += i_item_bytes_read;
  }

  return ptr;
}

NanoPack::TypeId Rpc::ListViewBatchOperations::type_id() const {
  return TYPE_ID;
}

size_t Rpc::ListViewBatchOperations::header_size() const { return 8; }

size_t Rpc::ListViewBatchOperations::write_to(NanoPack::Writer &writer,
                                              int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(8);

  writer.write_type_id(TYPE_ID, offset);

  const size_t operations_vec_size = operations.size();
  writer.append_int32(operations_vec_size);
  int32_t operations_byte_size = sizeof(int32_t);
  for (auto &i : operations) {
    const size_t i_byte_size = i->write_to(writer, writer.size());
    operations_byte_size += i_byte_size;
  }
  writer.write_field_size(0, operations_byte_size, offset);

  return writer.size() - writer_size_before;
}
