// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "list_view_item_config.np.hxx"

Rpc::ListViewItemConfig::ListViewItemConfig(
    std::optional<uint32_t> section_index, std::optional<uint32_t> item_index,
    std::optional<uint32_t> item_tag)
    : section_index(std::move(section_index)),
      item_index(std::move(item_index)), item_tag(std::move(item_tag)) {}

size_t Rpc::ListViewItemConfig::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 16;

  if (reader.read_field_size(0) < 0) {
    section_index = std::nullopt;
  } else {
    uint32_t section_index_value;
    reader.read_uint32(ptr, section_index_value);
    section_index = section_index_value;
    ptr += 4;
  }

  if (reader.read_field_size(1) < 0) {
    item_index = std::nullopt;
  } else {
    uint32_t item_index_value;
    reader.read_uint32(ptr, item_index_value);
    item_index = item_index_value;
    ptr += 4;
  }

  if (reader.read_field_size(2) < 0) {
    item_tag = std::nullopt;
  } else {
    uint32_t item_tag_value;
    reader.read_uint32(ptr, item_tag_value);
    item_tag = item_tag_value;
    ptr += 4;
  }

  return ptr;
}

NanoPack::TypeId Rpc::ListViewItemConfig::type_id() const { return TYPE_ID; }

size_t Rpc::ListViewItemConfig::header_size() const { return 16; }

size_t Rpc::ListViewItemConfig::write_to(NanoPack::Writer &writer,
                                         int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(16);

  writer.write_type_id(TYPE_ID, offset);

  if (section_index.has_value()) {
    writer.write_field_size(0, 4, offset);
    writer.append_uint32(*section_index);
  } else {
    writer.write_field_size(0, -1, offset);
  }

  if (item_index.has_value()) {
    writer.write_field_size(1, 4, offset);
    writer.append_uint32(*item_index);
  } else {
    writer.write_field_size(1, -1, offset);
  }

  if (item_tag.has_value()) {
    writer.write_field_size(2, 4, offset);
    writer.append_uint32(*item_tag);
  } else {
    writer.write_field_size(2, -1, offset);
  }

  return writer.size() - writer_size_before;
}
