// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "list_view_delete_operation.np.hxx"

Rpc::ListViewDeleteOperation::ListViewDeleteOperation(
    uint32_t tag, std::vector<int32_t> delete_at)
    : ListViewOperation(tag), delete_at(std::move(delete_at)) {}

size_t Rpc::ListViewDeleteOperation::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 12;

  reader.read_uint32(ptr, tag);
  ptr += 4;

  const int32_t delete_at_byte_size = reader.read_field_size(1);
  const int32_t delete_at_vec_size = delete_at_byte_size / 4;
  delete_at.resize(delete_at_vec_size);
  for (int i = 0; i < delete_at_vec_size; ++i) {
    auto &i_item = delete_at[i];
    reader.read_int32(ptr, i_item);
    ptr += 4;
  }

  return ptr;
}

NanoPack::TypeId Rpc::ListViewDeleteOperation::type_id() const {
  return TYPE_ID;
}

size_t Rpc::ListViewDeleteOperation::header_size() const { return 12; }

size_t Rpc::ListViewDeleteOperation::write_to(NanoPack::Writer &writer,
                                              int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(12);

  writer.write_type_id(TYPE_ID, offset);

  writer.write_field_size(0, 4, offset);
  writer.append_uint32(tag);

  const int32_t delete_at_byte_size = delete_at.size() * 4;
  writer.write_field_size(1, delete_at_byte_size, offset);
  for (const auto &i : delete_at) {
    writer.append_int32(i);
  }

  return writer.size() - writer_size_before;
}
