// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef LIST_VIEW_OPERATION_FACTORY_NP_HXX
#define LIST_VIEW_OPERATION_FACTORY_NP_HXX

#include "list_view_operation.np.hxx"
#include <memory>
#include <nanopack/reader.hxx>

namespace Rpc {

std::unique_ptr<ListViewOperation>
make_list_view_operation(NanoPack::Reader &reader, size_t &bytes_read);

} // namespace Rpc

#endif
