// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include "make_widget.np.hxx"

#include "button.np.hxx"
#include "center.np.hxx"
#include "column.np.hxx"
#include "list_view.np.hxx"
#include "row.np.hxx"
#include "slider.np.hxx"
#include "text.np.hxx"
#include "text_field.np.hxx"

std::unique_ptr<Rpc::Widget> Rpc::make_widget(NanoPack::Reader &reader,
                                              size_t &bytes_read) {
  switch (reader.read_type_id()) {
  case 1676374721: {
    auto ptr = std::make_unique<Widget>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 320412644: {
    auto ptr = std::make_unique<Button>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 841129444: {
    auto ptr = std::make_unique<TextField>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 1006836449: {
    auto ptr = std::make_unique<Row>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 1855640887: {
    auto ptr = std::make_unique<Center>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 2164488861: {
    auto ptr = std::make_unique<ListView>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 2415007766: {
    auto ptr = std::make_unique<Column>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 3373588321: {
    auto ptr = std::make_unique<Slider>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 3495336243: {
    auto ptr = std::make_unique<Text>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  default:
    return nullptr;
  }
}
