// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include "make_list_view_operation.np.hxx"

#include "list_view_delete_operation.np.hxx"
#include "list_view_insert_operation.np.hxx"

std::unique_ptr<Rpc::ListViewOperation>
Rpc::make_list_view_operation(NanoPack::Reader &reader, size_t &bytes_read) {
  switch (reader.read_type_id()) {
  case 3516816492: {
    auto ptr = std::make_unique<ListViewOperation>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 2077451345: {
    auto ptr = std::make_unique<ListViewInsertOperation>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 2223513129: {
    auto ptr = std::make_unique<ListViewDeleteOperation>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  default:
    return nullptr;
  }
}
