// AUTOMATICALLY GENERATED BY NANOC

#ifndef ROW_NP_HXX
#define ROW_NP_HXX
#include <memory>
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <vector>

#include "alignment.np.hxx"
#include "make_widget.np.hxx"
#include "widget.np.hxx"

namespace Rpc {

struct Row : Widget {
  static constexpr NanoPack::TypeId TYPE_ID = 1006836449;

  double width;
  double height;
  Alignment horizontal_alignment;
  Alignment vertical_alignment;
  std::vector<std::unique_ptr<Widget>> children;

  Row() = default;

  Row(std::optional<uint32_t> tag, double width, double height,
      const Alignment &horizontal_alignment,
      const Alignment &vertical_alignment,
      std::vector<std::unique_ptr<Widget>> children);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
