// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "slider.np.hxx"

Rpc::Slider::Slider(std::optional<uint32_t> tag, double value, double min_value,
                    double max_value, uint32_t on_value_changed, double width)
    : Widget(tag), value(value), min_value(min_value), max_value(max_value),
      on_value_changed(on_value_changed), width(width) {}

size_t Rpc::Slider::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 28;

  if (reader.read_field_size(0) < 0) {
    tag = std::nullopt;
  } else {
    uint32_t tag_value;
    reader.read_uint32(ptr, tag_value);
    tag = tag_value;
    ptr += 4;
  }

  reader.read_double(ptr, value);
  ptr += 8;

  reader.read_double(ptr, min_value);
  ptr += 8;

  reader.read_double(ptr, max_value);
  ptr += 8;

  reader.read_uint32(ptr, on_value_changed);
  ptr += 4;

  reader.read_double(ptr, width);
  ptr += 8;

  return ptr;
}

NanoPack::TypeId Rpc::Slider::type_id() const { return TYPE_ID; }

size_t Rpc::Slider::header_size() const { return 28; }

size_t Rpc::Slider::write_to(NanoPack::Writer &writer, int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(28);

  writer.write_type_id(TYPE_ID, offset);

  if (tag.has_value()) {
    writer.write_field_size(0, 4, offset);
    writer.append_uint32(*tag);
  } else {
    writer.write_field_size(0, -1, offset);
  }

  writer.write_field_size(1, 8, offset);
  writer.append_double(value);

  writer.write_field_size(2, 8, offset);
  writer.append_double(min_value);

  writer.write_field_size(3, 8, offset);
  writer.append_double(max_value);

  writer.write_field_size(4, 4, offset);
  writer.append_uint32(on_value_changed);

  writer.write_field_size(5, 8, offset);
  writer.append_double(width);

  return writer.size() - writer_size_before;
}
