// AUTOMATICALLY GENERATED BY NANOC

#ifndef SLIDER_VALUE_CHANGED_EVENT_NP_HXX
#define SLIDER_VALUE_CHANGED_EVENT_NP_HXX
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>

namespace Rpc {

struct SliderValueChangedEvent : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 1030062961;

  double new_value;

  SliderValueChangedEvent() = default;

  explicit SliderValueChangedEvent(double new_value);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
