// AUTOMATICALLY GENERATED BY NANOC

#ifndef SLIDER_NP_HXX
#define SLIDER_NP_HXX
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>

#include "make_widget.np.hxx"
#include "widget.np.hxx"

namespace Rpc {

struct Slider : Widget {
  static constexpr NanoPack::TypeId TYPE_ID = 3373588321;

  double value;
  double min_value;
  double max_value;
  uint32_t on_value_changed;
  double width;

  Slider() = default;

  Slider(std::optional<uint32_t> tag, double value, double min_value,
         double max_value, uint32_t on_value_changed, double width);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
