// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "slider_value_changed_event.np.hxx"

Rpc::SliderValueChangedEvent::SliderValueChangedEvent(double new_value)
    : new_value(new_value) {}

size_t Rpc::SliderValueChangedEvent::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 8;

  reader.read_double(ptr, new_value);
  ptr += 8;

  return ptr;
}

NanoPack::TypeId Rpc::SliderValueChangedEvent::type_id() const {
  return TYPE_ID;
}

size_t Rpc::SliderValueChangedEvent::header_size() const { return 8; }

size_t Rpc::SliderValueChangedEvent::write_to(NanoPack::Writer &writer,
                                              int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(8);

  writer.write_type_id(TYPE_ID, offset);

  writer.write_field_size(0, 8, offset);
  writer.append_double(new_value);

  return writer.size() - writer_size_before;
}
