// AUTOMATICALLY GENERATED BY NANOC

#ifndef TEXT_NP_HXX
#define TEXT_NP_HXX
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <string>

#include "font_style.np.hxx"
#include "make_widget.np.hxx"
#include "widget.np.hxx"

namespace Rpc {

struct Text : Widget {
  static constexpr NanoPack::TypeId TYPE_ID = 3495336243;

  std::string content;
  FontStyle style;

  Text() = default;

  Text(std::optional<uint32_t> tag, std::string content, FontStyle style);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
