// AUTOMATICALLY GENERATED BY NANOC

#ifndef TEXT_FIELD_NP_HXX
#define TEXT_FIELD_NP_HXX
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <optional>
#include <string>

#include "make_widget.np.hxx"
#include "widget.np.hxx"

namespace Rpc {

struct TextField : Widget {
  static constexpr NanoPack::TypeId TYPE_ID = 841129444;

  std::optional<std::string> placeholder;
  std::string value;
  uint32_t on_value_changed;

  TextField() = default;

  TextField(std::optional<uint32_t> tag, std::optional<std::string> placeholder,
            std::string value, uint32_t on_value_changed);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
