// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "text.np.hxx"

Rpc::Text::Text(std::optional<uint32_t> tag, std::string content,
                FontStyle style)
    : Widget(tag), content(std::move(content)), style(style) {}

size_t Rpc::Text::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 16;

  if (reader.read_field_size(0) < 0) {
    tag = std::nullopt;
  } else {
    uint32_t tag_value;
    reader.read_uint32(ptr, tag_value);
    tag = tag_value;
    ptr += 4;
  }

  const int32_t content_size = reader.read_field_size(1);
  reader.read_string(ptr, content_size, content);
  ptr += content_size;

  reader.buffer += ptr;
  const size_t style_bytes_read = style.read_from(reader);
  reader.buffer = buf;
  ptr += style_bytes_read;

  return ptr;
}

NanoPack::TypeId Rpc::Text::type_id() const { return TYPE_ID; }

size_t Rpc::Text::header_size() const { return 16; }

size_t Rpc::Text::write_to(NanoPack::Writer &writer, int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(16);

  writer.write_type_id(TYPE_ID, offset);

  if (tag.has_value()) {
    writer.write_field_size(0, 4, offset);
    writer.append_uint32(*tag);
  } else {
    writer.write_field_size(0, -1, offset);
  }

  writer.write_field_size(1, content.size(), offset);
  writer.append_string(content);

  const size_t style_byte_size = style.write_to(writer, writer.size());
  writer.write_field_size(2, style_byte_size, offset);

  return writer.size() - writer_size_before;
}
