// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "text_field.np.hxx"

Rpc::TextField::TextField(std::optional<uint32_t> tag,
                          std::optional<std::string> placeholder,
                          std::string value, uint32_t on_value_changed)
    : Widget(tag), placeholder(std::move(placeholder)), value(std::move(value)),
      on_value_changed(on_value_changed) {}

size_t Rpc::TextField::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 20;

  if (reader.read_field_size(0) < 0) {
    tag = std::nullopt;
  } else {
    uint32_t tag_value;
    reader.read_uint32(ptr, tag_value);
    tag = tag_value;
    ptr += 4;
  }

  if (reader.read_field_size(1) < 0) {
    placeholder = std::nullopt;
  } else {
    placeholder = std::move(std::string());
    const int32_t placeholder_size = reader.read_field_size(1);
    reader.read_string(ptr, placeholder_size, placeholder);
    ptr += placeholder_size;
  }

  const int32_t value_size = reader.read_field_size(2);
  reader.read_string(ptr, value_size, value);
  ptr += value_size;

  reader.read_uint32(ptr, on_value_changed);
  ptr += 4;

  return ptr;
}

NanoPack::TypeId Rpc::TextField::type_id() const { return TYPE_ID; }

size_t Rpc::TextField::header_size() const { return 20; }

size_t Rpc::TextField::write_to(NanoPack::Writer &writer, int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(20);

  writer.write_type_id(TYPE_ID, offset);

  if (tag.has_value()) {
    writer.write_field_size(0, 4, offset);
    writer.append_uint32(*tag);
  } else {
    writer.write_field_size(0, -1, offset);
  }

  if (placeholder.has_value()) {
    writer.write_field_size(1, placeholder->size(), offset);
    writer.append_string(*placeholder);
  } else {
    writer.write_field_size(1, -1, offset);
  }

  writer.write_field_size(2, value.size(), offset);
  writer.append_string(value);

  writer.write_field_size(3, 4, offset);
  writer.append_uint32(on_value_changed);

  return writer.size() - writer_size_before;
}
