// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "text_field_changed_event.np.hxx"

Rpc::TextFieldChangedEvent::TextFieldChangedEvent(std::string new_value)
    : new_value(std::move(new_value)) {}

size_t Rpc::TextFieldChangedEvent::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 8;

  const int32_t new_value_size = reader.read_field_size(0);
  reader.read_string(ptr, new_value_size, new_value);
  ptr += new_value_size;

  return ptr;
}

NanoPack::TypeId Rpc::TextFieldChangedEvent::type_id() const { return TYPE_ID; }

size_t Rpc::TextFieldChangedEvent::header_size() const { return 8; }

size_t Rpc::TextFieldChangedEvent::write_to(NanoPack::Writer &writer,
                                            int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(8);

  writer.write_type_id(TYPE_ID, offset);

  writer.write_field_size(0, new_value.size(), offset);
  writer.append_string(new_value);

  return writer.size() - writer_size_before;
}
