// AUTOMATICALLY GENERATED BY NANOC

#ifndef TEXT_FIELD_CHANGED_EVENT_NP_HXX
#define TEXT_FIELD_CHANGED_EVENT_NP_HXX
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <string>

namespace Rpc {

struct TextFieldChangedEvent : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 2286117075;

  std::string new_value;

  TextFieldChangedEvent() = default;

  explicit TextFieldChangedEvent(std::string new_value);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
