// AUTOMATICALLY GENERATED BY NANOC

#ifndef WIDGET_NP_HXX
#define WIDGET_NP_HXX
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <optional>

namespace Rpc {

struct Widget : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 1676374721;

  std::optional<uint32_t> tag;

  Widget() = default;

  explicit Widget(std::optional<uint32_t> tag);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
