// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef LIST_VIEW_ITEM_NP_HXX
#define LIST_VIEW_ITEM_NP_HXX

#include <memory>
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <vector>

#include "../make_widget.np.hxx"
#include "../widget.np.hxx"

namespace Poly::Message {

struct ListViewItem : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 1100735111;

  uint32_t item_tag;
  std::unique_ptr<Widget> widget;

  ListViewItem() = default;

  ListViewItem(uint32_t item_tag, std::unique_ptr<Widget> widget);

  ListViewItem(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  ListViewItem(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] Widget &get_widget() const;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;

  [[nodiscard]] std::vector<uint8_t> data_with_length_prefix() const override;
};

} // namespace Poly::Message

#endif
