// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef LIST_VIEW_INSERT_OPERATION_NP_HXX
#define LIST_VIEW_INSERT_OPERATION_NP_HXX

#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <vector>

#include "list_view_operation.np.hxx"
#include "make_list_view_operation.np.hxx"

namespace Poly::Message {

struct ListViewInsertOperation : ListViewOperation {
  static constexpr NanoPack::TypeId TYPE_ID = 2077451345;

  std::vector<int32_t> insert_at;

  ListViewInsertOperation() = default;

  ListViewInsertOperation(int32_t tag, std::vector<int32_t> insert_at);

  ListViewInsertOperation(std::vector<uint8_t>::const_iterator begin,
                          int &bytes_read);

  ListViewInsertOperation(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;

  [[nodiscard]] std::vector<uint8_t> data_with_length_prefix() const override;
};

} // namespace Poly::Message

#endif
