// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "list_view_operation.np.hxx"

Poly::Message::ListViewOperation::ListViewOperation(int32_t tag) : tag(tag) {}

Poly::Message::ListViewOperation::ListViewOperation(
    const NanoPack::Reader &reader, int &bytes_read) {
  const auto begin = reader.begin();
  int ptr = 8;

  const int32_t tag = reader.read_int32(ptr);
  ptr += 4;
  this->tag = tag;

  bytes_read = ptr;
}

Poly::Message::ListViewOperation::ListViewOperation(
    std::vector<uint8_t>::const_iterator begin, int &bytes_read)
    : ListViewOperation(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId Poly::Message::ListViewOperation::type_id() const {
  return TYPE_ID;
}

int Poly::Message::ListViewOperation::header_size() const { return 8; }

size_t Poly::Message::ListViewOperation::write_to(std::vector<uint8_t> &buf,
                                                  int offset) const {
  size_t bytes_written = 8;

  buf.resize(offset + 8);

  NanoPack::write_type_id(TYPE_ID, offset, buf);

  NanoPack::write_field_size(0, 4, offset, buf);
  NanoPack::append_int32(tag, buf);
  bytes_written += 4;

  return bytes_written;
}

std::vector<uint8_t> Poly::Message::ListViewOperation::data() const {
  std::vector<uint8_t> buf(8);
  write_to(buf, 0);
  return buf;
}
