// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "list_view_item_config.np.hxx"

Poly::Message::ListViewItemConfig::ListViewItemConfig(
    std::optional<uint32_t> section_index, std::optional<uint32_t> item_index,
    std::optional<int32_t> item_tag)
    : section_index(std::move(section_index)),
      item_index(std::move(item_index)), item_tag(std::move(item_tag)) {}

Poly::Message::ListViewItemConfig::ListViewItemConfig(
    const NanoPack::Reader &reader, int &bytes_read) {
  const auto begin = reader.begin();
  int ptr = 16;

  if (reader.read_field_size(0) < 0) {
    this->section_index = std::nullopt;
  } else {
    const uint32_t section_index = reader.read_uint32(ptr);
    ptr += 4;
    this->section_index = section_index;
  }

  if (reader.read_field_size(1) < 0) {
    this->item_index = std::nullopt;
  } else {
    const uint32_t item_index = reader.read_uint32(ptr);
    ptr += 4;
    this->item_index = item_index;
  }

  if (reader.read_field_size(2) < 0) {
    this->item_tag = std::nullopt;
  } else {
    const int32_t item_tag = reader.read_int32(ptr);
    ptr += 4;
    this->item_tag = item_tag;
  }

  bytes_read = ptr;
}

Poly::Message::ListViewItemConfig::ListViewItemConfig(
    std::vector<uint8_t>::const_iterator begin, int &bytes_read)
    : ListViewItemConfig(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId Poly::Message::ListViewItemConfig::type_id() const {
  return TYPE_ID;
}

int Poly::Message::ListViewItemConfig::header_size() const { return 16; }

size_t Poly::Message::ListViewItemConfig::write_to(std::vector<uint8_t> &buf,
                                                   int offset) const {
  size_t bytes_written = 16;

  buf.resize(offset + 16);

  NanoPack::write_type_id(TYPE_ID, offset, buf);

  if (section_index.has_value()) {
    const auto section_index = this->section_index.value();
    NanoPack::write_field_size(0, 4, offset, buf);
    NanoPack::append_uint32(section_index, buf);
    bytes_written += 4;
  } else {
    NanoPack::write_field_size(0, -1, offset, buf);
  }

  if (item_index.has_value()) {
    const auto item_index = this->item_index.value();
    NanoPack::write_field_size(1, 4, offset, buf);
    NanoPack::append_uint32(item_index, buf);
    bytes_written += 4;
  } else {
    NanoPack::write_field_size(1, -1, offset, buf);
  }

  if (item_tag.has_value()) {
    const auto item_tag = this->item_tag.value();
    NanoPack::write_field_size(2, 4, offset, buf);
    NanoPack::append_int32(item_tag, buf);
    bytes_written += 4;
  } else {
    NanoPack::write_field_size(2, -1, offset, buf);
  }

  return bytes_written;
}

std::vector<uint8_t> Poly::Message::ListViewItemConfig::data() const {
  std::vector<uint8_t> buf(16);
  write_to(buf, 0);
  return buf;
}
