// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef LIST_VIEW_ITEM_CONFIG_NP_HXX
#define LIST_VIEW_ITEM_CONFIG_NP_HXX

#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <optional>
#include <vector>

namespace Poly::Message {

struct ListViewItemConfig : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 4128951807;

  std::optional<uint32_t> section_index;
  std::optional<uint32_t> item_index;
  std::optional<int32_t> item_tag;

  ListViewItemConfig() = default;

  ListViewItemConfig(std::optional<uint32_t> section_index,
                     std::optional<uint32_t> item_index,
                     std::optional<int32_t> item_tag);

  ListViewItemConfig(std::vector<uint8_t>::const_iterator begin,
                     int &bytes_read);

  ListViewItemConfig(const NanoPack::Reader &reader, int &bytes_read);

  size_t write_to(std::vector<uint8_t> &buf, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] int header_size() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;
};

} // namespace Poly::Message

#endif
