// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "list_view_insert_operation.np.hxx"

Poly::Message::ListViewInsertOperation::ListViewInsertOperation(
    int32_t tag, std::vector<int32_t> insert_at)
    : ListViewOperation(tag), insert_at(std::move(insert_at)) {}

Poly::Message::ListViewInsertOperation::ListViewInsertOperation(
    const NanoPack::Reader &reader, int &bytes_read)
    : ListViewOperation() {
  const auto begin = reader.begin();
  int ptr = 12;

  const int32_t tag = reader.read_int32(ptr);
  ptr += 4;
  this->tag = tag;

  const int32_t insert_at_byte_size = reader.read_field_size(1);
  const int32_t insert_at_vec_size = insert_at_byte_size / 4;
  std::vector<int32_t> insert_at;
  insert_at.reserve(insert_at_vec_size);
  for (int i = 0; i < insert_at_vec_size; i++) {
    const int32_t i_item = reader.read_int32(ptr);
    ptr += 4;
    insert_at.emplace_back(std::move(i_item));
  }
  this->insert_at = std::move(insert_at);

  bytes_read = ptr;
}

Poly::Message::ListViewInsertOperation::ListViewInsertOperation(
    std::vector<uint8_t>::const_iterator begin, int &bytes_read)
    : ListViewInsertOperation(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId Poly::Message::ListViewInsertOperation::type_id() const {
  return TYPE_ID;
}

int Poly::Message::ListViewInsertOperation::header_size() const { return 12; }

size_t
Poly::Message::ListViewInsertOperation::write_to(std::vector<uint8_t> &buf,
                                                 int offset) const {
  size_t bytes_written = 12;

  buf.resize(offset + 12);

  NanoPack::write_type_id(TYPE_ID, offset, buf);

  NanoPack::write_field_size(0, 4, offset, buf);
  NanoPack::append_int32(tag, buf);
  bytes_written += 4;

  const int32_t insert_at_byte_size = insert_at.size() * 4;
  NanoPack::write_field_size(1, insert_at_byte_size, offset, buf);
  for (const auto &i : insert_at) {
    NanoPack::append_int32(i, buf);
  }
  bytes_written += insert_at_byte_size;

  return bytes_written;
}

std::vector<uint8_t> Poly::Message::ListViewInsertOperation::data() const {
  std::vector<uint8_t> buf(12);
  write_to(buf, 0);
  return buf;
}
