// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef LIST_VIEW_OPERATION_NP_HXX
#define LIST_VIEW_OPERATION_NP_HXX

#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <vector>

namespace Poly::Message {

struct ListViewOperation : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 3516816492;

  int32_t tag;

  ListViewOperation() = default;

  explicit ListViewOperation(int32_t tag);

  ListViewOperation(std::vector<uint8_t>::const_iterator begin,
                    int &bytes_read);

  ListViewOperation(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;

  [[nodiscard]] std::vector<uint8_t> data_with_length_prefix() const override;
};

} // namespace Poly::Message

#endif
