// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include "make_list_view_operation.np.hxx"
#include <nanopack/reader.hxx>

#include "list_view_delete_operation.np.hxx"
#include "list_view_insert_operation.np.hxx"

std::unique_ptr<Poly::Message::ListViewOperation>
Poly::Message::make_list_view_operation(
    std::vector<uint8_t>::const_iterator begin, int &bytes_read) {
  const NanoPack::Reader reader(begin);
  switch (reader.read_type_id()) {
  case 3516816492:
    return std::make_unique<ListViewOperation>(reader, bytes_read);
  case 2077451345:
    return std::make_unique<ListViewInsertOperation>(reader, bytes_read);
  case 2223513129:
    return std::make_unique<ListViewDeleteOperation>(reader, bytes_read);
  default:
    return nullptr;
  }
}
