// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef RENDER_ITEM_CONFIG_NP_HXX
#define RENDER_ITEM_CONFIG_NP_HXX

#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <optional>
#include <vector>

namespace Poly::Message {

struct RenderItemConfig : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 3591753548;

  int32_t section_index;
  int32_t item_index;
  std::optional<int32_t> item_tag;

  RenderItemConfig() = default;

  RenderItemConfig(int32_t section_index, int32_t item_index,
                   std::optional<int32_t> item_tag);

  RenderItemConfig(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  RenderItemConfig(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;

  [[nodiscard]] std::vector<uint8_t> data_with_length_prefix() const override;
};

} // namespace Poly::Message

#endif
