// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include "nanopack_message_factory.np.hxx"

#include "event/click_event.np.hxx"
#include "widget/button.np.hxx"
#include "widget/center.np.hxx"
#include "widget/column.np.hxx"
#include "widget/font_style.np.hxx"
#include "widget/list_view.np.hxx"
#include "widget/list_view_batch_operations.np.hxx"
#include "widget/list_view_delete_operation.np.hxx"
#include "widget/list_view_insert_operation.np.hxx"
#include "widget/list_view_item.np.hxx"
#include "widget/list_view_item_config.np.hxx"
#include "widget/list_view_operation.np.hxx"
#include "widget/row.np.hxx"
#include "widget/slider.np.hxx"
#include "widget/slider_value_changed_event.np.hxx"
#include "widget/text.np.hxx"
#include "widget/text_field.np.hxx"
#include "widget/text_field_changed_event.np.hxx"
#include "widget/widget.np.hxx"

std::unique_ptr<NanoPack::Message>
Rpc::make_nanopack_message(NanoPack::Reader &reader) {
  size_t _;
  return make_nanopack_message(reader, _);
}

std::unique_ptr<NanoPack::Message>
Rpc::make_nanopack_message(NanoPack::Reader &reader, size_t &bytes_read) {
  switch (reader.read_type_id()) {
  case 320412644: {
    auto ptr = std::make_unique<Button>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 837166865: {
    auto ptr = std::make_unique<ClickEvent>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 841129444: {
    auto ptr = std::make_unique<TextField>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 1006836449: {
    auto ptr = std::make_unique<Row>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 1030062961: {
    auto ptr = std::make_unique<SliderValueChangedEvent>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 1100735111: {
    auto ptr = std::make_unique<ListViewItem>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 1676374721: {
    auto ptr = std::make_unique<Widget>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 1855640887: {
    auto ptr = std::make_unique<Center>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 2077451345: {
    auto ptr = std::make_unique<ListViewInsertOperation>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 2164488861: {
    auto ptr = std::make_unique<ListView>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 2223513129: {
    auto ptr = std::make_unique<ListViewDeleteOperation>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 2286117075: {
    auto ptr = std::make_unique<TextFieldChangedEvent>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 2415007766: {
    auto ptr = std::make_unique<Column>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 3373588321: {
    auto ptr = std::make_unique<Slider>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 3495336243: {
    auto ptr = std::make_unique<Text>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 3516816492: {
    auto ptr = std::make_unique<ListViewOperation>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 3604546751: {
    auto ptr = std::make_unique<ListViewBatchOperations>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 3635009167: {
    auto ptr = std::make_unique<FontStyle>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 4128951807: {
    auto ptr = std::make_unique<ListViewItemConfig>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  default:
    return nullptr;
  }
}
