// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef CREATE_WINDOW_NP_HXX
#define CREATE_WINDOW_NP_HXX

#include <nanopack/message.hxx>
#include <nanopack/reader.hxx>
#include <string>
#include <vector>

struct CreateWindow : NanoPack::Message {
  static constexpr int32_t TYPE_ID = 10;

  std::string title;
  std::string description;
  int32_t width;
  int32_t height;
  std::string tag;

  CreateWindow() = default;

  CreateWindow(std::string title, std::string description, int32_t width,
               int32_t height, std::string tag);

  CreateWindow(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  CreateWindow(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] int32_t type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;
};

#endif
