// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "create_window.np.hxx"

Poly::Message::CreateWindow::CreateWindow(std::string title,
                                          std::string description,
                                          int32_t width, int32_t height,
                                          std::string tag)
    : title(std::move(title)), description(std::move(description)),
      width(width), height(height), tag(std::move(tag)) {}

Poly::Message::CreateWindow::CreateWindow(const NanoPack::Reader &reader,
                                          int &bytes_read) {
  const auto begin = reader.begin();
  int ptr = 24;

  const int32_t title_size = reader.read_field_size(0);
  title = reader.read_string(ptr, title_size);
  ptr += title_size;

  const int32_t description_size = reader.read_field_size(1);
  description = reader.read_string(ptr, description_size);
  ptr += description_size;

  const int32_t width = reader.read_int32(ptr);
  ptr += 4;
  this->width = width;

  const int32_t height = reader.read_int32(ptr);
  ptr += 4;
  this->height = height;

  const int32_t tag_size = reader.read_field_size(4);
  tag = reader.read_string(ptr, tag_size);
  ptr += tag_size;

  bytes_read = ptr;
}

Poly::Message::CreateWindow::CreateWindow(
    std::vector<uint8_t>::const_iterator begin, int &bytes_read)
    : CreateWindow(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId Poly::Message::CreateWindow::type_id() const {
  return TYPE_ID;
}

int Poly::Message::CreateWindow::header_size() const { return 24; }

size_t Poly::Message::CreateWindow::write_to(std::vector<uint8_t> &buf,
                                             int offset) const {
  size_t bytes_written = 24;

  buf.resize(offset + 24);

  NanoPack::write_type_id(TYPE_ID, offset, buf);

  NanoPack::write_field_size(0, title.size(), offset, buf);
  NanoPack::append_string(title, buf);
  bytes_written += title.size();

  NanoPack::write_field_size(1, description.size(), offset, buf);
  NanoPack::append_string(description, buf);
  bytes_written += description.size();

  NanoPack::write_field_size(2, 4, offset, buf);
  NanoPack::append_int32(width, buf);
  bytes_written += 4;

  NanoPack::write_field_size(3, 4, offset, buf);
  NanoPack::append_int32(height, buf);
  bytes_written += 4;

  NanoPack::write_field_size(4, tag.size(), offset, buf);
  NanoPack::append_string(tag, buf);
  bytes_written += tag.size();

  return bytes_written;
}

std::vector<uint8_t> Poly::Message::CreateWindow::data() const {
  std::vector<uint8_t> buf(24);
  write_to(buf, 0);
  return buf;
}
