// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include "nanopack_message_factory.np.hxx"

#include "create_window.np.hxx"
#include "invoke_callback.np.hxx"
#include "ok_response.np.hxx"
#include "reply_from_callback.np.hxx"
#include "request.np.hxx"
#include "widgets/button/button.np.hxx"
#include "widgets/button/click_event.np.hxx"
#include "widgets/center.np.hxx"
#include "widgets/column.np.hxx"
#include "widgets/create_widget.np.hxx"
#include "widgets/list_view/list_view.np.hxx"
#include "widgets/list_view/list_view_batch_operations.np.hxx"
#include "widgets/list_view/list_view_delete_operation.np.hxx"
#include "widgets/list_view/list_view_insert_operation.np.hxx"
#include "widgets/list_view/list_view_item.np.hxx"
#include "widgets/list_view/list_view_item_config.np.hxx"
#include "widgets/list_view/list_view_operation.np.hxx"
#include "widgets/row.np.hxx"
#include "widgets/text.np.hxx"
#include "widgets/text_field/on_value_changed.np.hxx"
#include "widgets/text_field/text_field.np.hxx"
#include "widgets/update_widget.np.hxx"
#include "widgets/update_widgets.np.hxx"
#include "widgets/widget.np.hxx"

std::unique_ptr<NanoPack::Message> Poly::Message::make_nanopack_message(
    std::vector<uint8_t>::const_iterator data_iter, int &bytes_read) {
  switch (const NanoPack::Reader reader(data_iter); reader.read_type_id()) {
  case 320412644:
    return std::make_unique<Button>(reader, bytes_read);
  case 370365707:
    return std::make_unique<ReplyFromCallback>(reader, bytes_read);
  case 624966581:
    return std::make_unique<UpdateWidgets>(reader, bytes_read);
  case 837166865:
    return std::make_unique<ClickEvent>(reader, bytes_read);
  case 841129444:
    return std::make_unique<TextField>(reader, bytes_read);
  case 879254966:
    return std::make_unique<Request>(reader, bytes_read);
  case 1006836449:
    return std::make_unique<Row>(reader, bytes_read);
  case 1016534798:
    return std::make_unique<UpdateWidget>(reader, bytes_read);
  case 1100735111:
    return std::make_unique<ListViewItem>(reader, bytes_read);
  case 1144955386:
    return std::make_unique<OkResponse>(reader, bytes_read);
  case 1676374721:
    return std::make_unique<Widget>(reader, bytes_read);
  case 1768749598:
    return std::make_unique<OnValueChanged>(reader, bytes_read);
  case 1855640887:
    return std::make_unique<Center>(reader, bytes_read);
  case 2013877267:
    return std::make_unique<InvokeCallback>(reader, bytes_read);
  case 2077451345:
    return std::make_unique<ListViewInsertOperation>(reader, bytes_read);
  case 2164488861:
    return std::make_unique<ListView>(reader, bytes_read);
  case 2223513129:
    return std::make_unique<ListViewDeleteOperation>(reader, bytes_read);
  case 2313387354:
    return std::make_unique<CreateWidget>(reader, bytes_read);
  case 2415007766:
    return std::make_unique<Column>(reader, bytes_read);
  case 3495336243:
    return std::make_unique<Text>(reader, bytes_read);
  case 3516816492:
    return std::make_unique<ListViewOperation>(reader, bytes_read);
  case 3533765426:
    return std::make_unique<CreateWindow>(reader, bytes_read);
  case 3604546751:
    return std::make_unique<ListViewBatchOperations>(reader, bytes_read);
  case 4128951807:
    return std::make_unique<ListViewItemConfig>(reader, bytes_read);
  default:
    return nullptr;
  }
}
