// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "ok_response.np.hxx"

Poly::Message::OkResponse::OkResponse(uint32_t request_id,
                                      std::optional<NanoPack::Any> body)
    : request_id(request_id), body(std::move(body)) {}

Poly::Message::OkResponse::OkResponse(const NanoPack::Reader &reader,
                                      int &bytes_read) {
  const auto begin = reader.begin();
  int ptr = 12;

  const uint32_t request_id = reader.read_uint32(ptr);
  ptr += 4;
  this->request_id = request_id;

  if (reader.read_field_size(1) < 0) {
    this->body = std::nullopt;
  } else {
    const int32_t body_byte_size = reader.read_field_size(1);
    body = NanoPack::Any(begin + ptr, begin + ptr + body_byte_size);
    ptr += body_byte_size;
  }

  bytes_read = ptr;
}

Poly::Message::OkResponse::OkResponse(
    std::vector<uint8_t>::const_iterator begin, int &bytes_read)
    : OkResponse(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId Poly::Message::OkResponse::type_id() const { return TYPE_ID; }

int Poly::Message::OkResponse::header_size() const { return 12; }

size_t Poly::Message::OkResponse::write_to(std::vector<uint8_t> &buf,
                                           int offset) const {
  size_t bytes_written = 12;

  buf.resize(offset + 12);

  NanoPack::write_type_id(TYPE_ID, offset, buf);

  NanoPack::write_field_size(0, 4, offset, buf);
  NanoPack::append_uint32(request_id, buf);
  bytes_written += 4;

  if (body.has_value()) {
    const auto body = this->body.value();
    NanoPack::write_field_size(1, body.size(), offset, buf);
    NanoPack::append_bytes(body.data(), buf);
    bytes_written += body.size();
  } else {
    NanoPack::write_field_size(1, -1, offset, buf);
  }

  return bytes_written;
}

std::vector<uint8_t> Poly::Message::OkResponse::data() const {
  std::vector<uint8_t> buf(12);
  write_to(buf, 0);
  return buf;
}
