// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef OK_RESPONSE_NP_HXX
#define OK_RESPONSE_NP_HXX

#include <nanopack/any.hxx>
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <optional>
#include <vector>

namespace Poly::Message {

struct OkResponse : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 1144955386;

  uint32_t request_id;
  std::optional<NanoPack::Any> body;

  OkResponse() = default;

  OkResponse(uint32_t request_id, std::optional<NanoPack::Any> body);

  OkResponse(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  OkResponse(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;

  [[nodiscard]] std::vector<uint8_t> data_with_length_prefix() const override;
};

} // namespace Poly::Message

#endif
