// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef REPLY_FROM_CALLBACK_NP_HXX
#define REPLY_FROM_CALLBACK_NP_HXX

#include <nanopack/any.hxx>
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <vector>

namespace Poly::Message {

struct ReplyFromCallback : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 370365707;

  int32_t to;
  NanoPack::Any args;

  ReplyFromCallback() = default;

  ReplyFromCallback(int32_t to, NanoPack::Any args);

  ReplyFromCallback(std::vector<uint8_t>::const_iterator begin,
                    int &bytes_read);

  ReplyFromCallback(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;

  [[nodiscard]] std::vector<uint8_t> data_with_length_prefix() const override;
};

} // namespace Poly::Message

#endif
