// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "reply_from_callback.np.hxx"

Poly::Message::ReplyFromCallback::ReplyFromCallback(int32_t to,
                                                    NanoPack::Any args)
    : to(to), args(std::move(args)) {}

Poly::Message::ReplyFromCallback::ReplyFromCallback(
    const NanoPack::Reader &reader, int &bytes_read) {
  const auto begin = reader.begin();
  int ptr = 12;

  const int32_t to = reader.read_int32(ptr);
  ptr += 4;
  this->to = to;

  const int32_t args_byte_size = reader.read_field_size(1);
  args = NanoPack::Any(begin + ptr, begin + ptr + args_byte_size);
  ptr += args_byte_size;

  bytes_read = ptr;
}

Poly::Message::ReplyFromCallback::ReplyFromCallback(
    std::vector<uint8_t>::const_iterator begin, int &bytes_read)
    : ReplyFromCallback(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId Poly::Message::ReplyFromCallback::type_id() const {
  return TYPE_ID;
}

int Poly::Message::ReplyFromCallback::header_size() const { return 12; }

size_t Poly::Message::ReplyFromCallback::write_to(std::vector<uint8_t> &buf,
                                                  int offset) const {
  size_t bytes_written = 12;

  buf.resize(offset + 12);

  NanoPack::write_type_id(TYPE_ID, offset, buf);

  NanoPack::write_field_size(0, 4, offset, buf);
  NanoPack::append_int32(to, buf);
  bytes_written += 4;

  NanoPack::write_field_size(1, args.size(), offset, buf);
  NanoPack::append_bytes(args.data(), buf);
  bytes_written += args.size();

  return bytes_written;
}

std::vector<uint8_t> Poly::Message::ReplyFromCallback::data() const {
  std::vector<uint8_t> buf(12);
  write_to(buf, 0);
  return buf;
}
