// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "request.np.hxx"

Poly::Message::Request::Request(uint32_t id, NanoPack::Any body)
    : id(id), body(std::move(body)) {}

Poly::Message::Request::Request(const NanoPack::Reader &reader,
                                int &bytes_read) {
  const auto begin = reader.begin();
  int ptr = 12;

  const uint32_t id = reader.read_uint32(ptr);
  ptr += 4;
  this->id = id;

  const int32_t body_byte_size = reader.read_field_size(1);
  body = NanoPack::Any(begin + ptr, begin + ptr + body_byte_size);
  ptr += body_byte_size;

  bytes_read = ptr;
}

Poly::Message::Request::Request(std::vector<uint8_t>::const_iterator begin,
                                int &bytes_read)
    : Request(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId Poly::Message::Request::type_id() const { return TYPE_ID; }

std::vector<uint8_t> Poly::Message::Request::data() const {
  std::vector<uint8_t> buf(12);
  NanoPack::Writer writer(&buf);

  writer.write_type_id(TYPE_ID);

  writer.write_field_size(0, 4);
  writer.append_uint32(id);

  writer.write_field_size(1, body.size());
  writer.append_bytes(body.data());

  return buf;
}

std::vector<uint8_t> Poly::Message::Request::data_with_length_prefix() const {
  std::vector<uint8_t> buf(12 + 4);
  NanoPack::Writer writer(&buf, 4);

  writer.write_type_id(TYPE_ID);

  writer.write_field_size(0, 4);
  writer.append_uint32(id);

  writer.write_field_size(1, body.size());
  writer.append_bytes(body.data());

  const size_t byte_size = buf.size() - 4;
  buf[0] = byte_size & 0xFF;
  buf[1] = byte_size & 0xFF00;
  buf[2] = byte_size & 0xFF0000;
  buf[3] = byte_size & 0xFF000000;

  return buf;
}
