// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef ON_VALUE_CHANGED_NP_HXX
#define ON_VALUE_CHANGED_NP_HXX

#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <string>
#include <vector>

namespace Poly::Message {

struct OnValueChanged : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 1768749598;

  std::string new_value;

  OnValueChanged() = default;

  explicit OnValueChanged(std::string new_value);

  OnValueChanged(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  OnValueChanged(const NanoPack::Reader &reader, int &bytes_read);

  size_t write_to(std::vector<uint8_t> &buf, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] int header_size() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;
};

} // namespace Poly::Message

#endif
