// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef ON_VALUE_CHANGED_NP_HXX
#define ON_VALUE_CHANGED_NP_HXX

#include <nanopack/message.hxx>
#include <nanopack/reader.hxx>
#include <string>
#include <vector>

namespace Poly::Message {

struct OnValueChanged : NanoPack::Message {
  static constexpr int32_t TYPE_ID = 1051;

  std::string new_value;

  OnValueChanged() = default;

  explicit OnValueChanged(std::string new_value);

  OnValueChanged(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  OnValueChanged(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] int32_t type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;

  [[nodiscard]] std::vector<uint8_t> data_with_length_prefix() const override;
};

} // namespace Poly::Message

#endif
