// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "text_field.np.hxx"

Poly::Message::TextField::TextField(std::optional<int32_t> tag,
                                    std::optional<std::string> placeholder,
                                    std::string value, int32_t on_value_changed)
    : Widget(tag), placeholder(std::move(placeholder)), value(std::move(value)),
      on_value_changed(on_value_changed) {}

Poly::Message::TextField::TextField(const NanoPack::Reader &reader,
                                    int &bytes_read)
    : Widget() {
  const auto begin = reader.begin();
  int ptr = 20;

  if (reader.read_field_size(0) < 0) {
    this->tag = std::nullopt;
  } else {
    const int32_t tag = reader.read_int32(ptr);
    ptr += 4;
    this->tag = tag;
  }

  if (reader.read_field_size(1) < 0) {
    this->placeholder = std::nullopt;
  } else {
    const int32_t placeholder_size = reader.read_field_size(1);
    placeholder = reader.read_string(ptr, placeholder_size);
    ptr += placeholder_size;
  }

  const int32_t value_size = reader.read_field_size(2);
  value = reader.read_string(ptr, value_size);
  ptr += value_size;

  const int32_t on_value_changed = reader.read_int32(ptr);
  ptr += 4;
  this->on_value_changed = on_value_changed;

  bytes_read = ptr;
}

Poly::Message::TextField::TextField(std::vector<uint8_t>::const_iterator begin,
                                    int &bytes_read)
    : TextField(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId Poly::Message::TextField::type_id() const { return TYPE_ID; }

int Poly::Message::TextField::header_size() const { return 20; }

size_t Poly::Message::TextField::write_to(std::vector<uint8_t> &buf,
                                          int offset) const {
  size_t bytes_written = 20;

  buf.resize(offset + 20);

  NanoPack::write_type_id(TYPE_ID, offset, buf);

  if (tag.has_value()) {
    const auto tag = this->tag.value();
    NanoPack::write_field_size(0, 4, offset, buf);
    NanoPack::append_int32(tag, buf);
    bytes_written += 4;
  } else {
    NanoPack::write_field_size(0, -1, offset, buf);
  }

  if (placeholder.has_value()) {
    const auto placeholder = this->placeholder.value();
    NanoPack::write_field_size(1, placeholder.size(), offset, buf);
    NanoPack::append_string(placeholder, buf);
    bytes_written += placeholder.size();
  } else {
    NanoPack::write_field_size(1, -1, offset, buf);
  }

  NanoPack::write_field_size(2, value.size(), offset, buf);
  NanoPack::append_string(value, buf);
  bytes_written += value.size();

  NanoPack::write_field_size(3, 4, offset, buf);
  NanoPack::append_int32(on_value_changed, buf);
  bytes_written += 4;

  return bytes_written;
}

std::vector<uint8_t> Poly::Message::TextField::data() const {
  std::vector<uint8_t> buf(20);
  write_to(buf, 0);
  return buf;
}
