// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "center.np.hxx"

Poly::Message::Center::Center(std::optional<int32_t> tag,
                              std::unique_ptr<Widget> child)
    : Widget(tag), child(std::move(child)) {}

Poly::Message::Center::Center(const NanoPack::Reader &reader, int &bytes_read)
    : Widget() {
  const auto begin = reader.begin();
  int ptr = 12;

  if (reader.read_field_size(0) < 0) {
    this->tag = std::nullopt;
  } else {
    const int32_t tag = reader.read_int32(ptr);
    ptr += 4;
    this->tag = tag;
  }

  int child_bytes_read = 0;
  child = std::move(make_widget(begin + ptr, child_bytes_read));
  ptr += child_bytes_read;

  bytes_read = ptr;
}

Poly::Message::Center::Center(std::vector<uint8_t>::const_iterator begin,
                              int &bytes_read)
    : Center(NanoPack::Reader(begin), bytes_read) {}

Poly::Message::Widget &Poly::Message::Center::get_child() const {
  return *child;
}

NanoPack::TypeId Poly::Message::Center::type_id() const { return TYPE_ID; }

int Poly::Message::Center::header_size() const { return 12; }

size_t Poly::Message::Center::write_to(std::vector<uint8_t> &buf,
                                       int offset) const {
  size_t bytes_written = 12;

  buf.resize(offset + 12);

  NanoPack::write_type_id(TYPE_ID, offset, buf);

  if (tag.has_value()) {
    const auto tag = this->tag.value();
    NanoPack::write_field_size(0, 4, offset, buf);
    NanoPack::append_int32(tag, buf);
    bytes_written += 4;
  } else {
    NanoPack::write_field_size(0, -1, offset, buf);
  }

  const size_t child_byte_size = child->write_to(buf, buf.size());
  NanoPack::write_field_size(1, child_byte_size, offset, buf);

  return bytes_written;
}

std::vector<uint8_t> Poly::Message::Center::data() const {
  std::vector<uint8_t> buf(12);
  write_to(buf, 0);
  return buf;
}
