// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef CENTER_NP_HXX
#define CENTER_NP_HXX

#include <nanopack/reader.hxx>
#include <vector>

#include "widget.np.hxx"

struct Center : Widget {
  static constexpr int32_t TYPE_ID = 102;

  Widget child;

  Center() = default;

  Center(std::optional<int32_t> tag, Widget child);

  Center(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  Center(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] int32_t type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;
};

#endif
