// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef CREATE_WIDGET_NP_HXX
#define CREATE_WIDGET_NP_HXX

#include <nanopack/message.hxx>
#include <nanopack/reader.hxx>
#include <string>
#include <vector>

#include "widget.np.hxx"

struct CreateWidget : NanoPack::Message {
  static constexpr int32_t TYPE_ID = 20;

  Widget widget;
  std::string window_tag;

  CreateWidget() = default;

  CreateWidget(Widget widget, std::string window_tag);

  CreateWidget(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  CreateWidget(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] int32_t type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;
};

#endif
