// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef FONT_STYLE_NP_HXX
#define FONT_STYLE_NP_HXX

#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <string>
#include <vector>

namespace Poly::Message {

struct FontStyle : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 3635009167;

  std::string font_family;
  uint32_t font_weight;
  uint32_t font_size;

  FontStyle() = default;

  FontStyle(std::string font_family, uint32_t font_weight, uint32_t font_size);

  FontStyle(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  FontStyle(const NanoPack::Reader &reader, int &bytes_read);

  size_t write_to(std::vector<uint8_t> &buf, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] int header_size() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;
};

} // namespace Poly::Message

#endif
