// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include "make_widget.np.hxx"
#include <nanopack/reader.hxx>

#include "button/button.np.hxx"
#include "center.np.hxx"
#include "column.np.hxx"
#include "text.np.hxx"

std::unique_ptr<Poly::Message::Widget>
Poly::Message::make_widget(std::vector<uint8_t>::const_iterator begin,
                           int &bytes_read) {
  const NanoPack::Reader reader(begin);
  switch (reader.read_type_id()) {
  case 100:
    return std::make_unique<Widget>(reader, bytes_read);
  case 103:
    return std::make_unique<Column>(reader, bytes_read);
  case 101:
    return std::make_unique<Text>(reader, bytes_read);
  case 104:
    return std::make_unique<Button>(reader, bytes_read);
  case 102:
    return std::make_unique<Center>(reader, bytes_read);
  default:
    return nullptr;
  }
}
