// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include "make_widget.np.hxx"
#include <nanopack/reader.hxx>

#include "button/button.np.hxx"
#include "center.np.hxx"
#include "column.np.hxx"
#include "list_view/list_view.np.hxx"
#include "row.np.hxx"
#include "text.np.hxx"
#include "text_field/text_field.np.hxx"

std::unique_ptr<Poly::Message::Widget>
Poly::Message::make_widget(std::vector<uint8_t>::const_iterator begin,
                           int &bytes_read) {
  const NanoPack::Reader reader(begin);
  switch (reader.read_type_id()) {
  case 1676374721:
    return std::make_unique<Widget>(reader, bytes_read);
  case 320412644:
    return std::make_unique<Button>(reader, bytes_read);
  case 841129444:
    return std::make_unique<TextField>(reader, bytes_read);
  case 1006836449:
    return std::make_unique<Row>(reader, bytes_read);
  case 1855640887:
    return std::make_unique<Center>(reader, bytes_read);
  case 2164488861:
    return std::make_unique<ListView>(reader, bytes_read);
  case 2415007766:
    return std::make_unique<Column>(reader, bytes_read);
  case 3495336243:
    return std::make_unique<Text>(reader, bytes_read);
  default:
    return nullptr;
  }
}
