// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef WIDGET_FACTORY_NP_HXX
#define WIDGET_FACTORY_NP_HXX

#include "widget.np.hxx"
#include <memory>

namespace Poly::Message {

std::unique_ptr<Widget> make_widget(std::vector<uint8_t>::const_iterator begin,
                                    int &bytes_read);

} // namespace Poly::Message

#endif
