// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "text.np.hxx"

Poly::Message::Text::Text(std::optional<int32_t> tag, std::string content)
    : Widget(tag), content(std::move(content)) {}

Poly::Message::Text::Text(const NanoPack::Reader &reader, int &bytes_read)
    : Widget() {
  const auto begin = reader.begin();
  int ptr = 12;

  if (reader.read_field_size(0) < 0) {
    this->tag = std::nullopt;
  } else {
    const int32_t tag = reader.read_int32(ptr);
    ptr += 4;
    this->tag = tag;
  }

  const int32_t content_size = reader.read_field_size(1);
  content = reader.read_string(ptr, content_size);
  ptr += content_size;

  bytes_read = ptr;
}

Poly::Message::Text::Text(std::vector<uint8_t>::const_iterator begin,
                          int &bytes_read)
    : Text(NanoPack::Reader(begin), bytes_read) {}

int32_t Poly::Message::Text::type_id() const { return TYPE_ID; }

std::vector<uint8_t> Poly::Message::Text::data() const {
  std::vector<uint8_t> buf(12);
  NanoPack::Writer writer(&buf);

  writer.write_type_id(TYPE_ID);

  if (tag.has_value()) {
    const auto tag = this->tag.value();
    writer.write_field_size(0, 4);
    writer.append_int32(tag);
  } else {
    writer.write_field_size(0, -1);
  }

  writer.write_field_size(1, content.size());
  writer.append_string(content);

  return buf;
}
