// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef TEXT_NP_HXX
#define TEXT_NP_HXX

#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <string>
#include <vector>

#include "font_style.np.hxx"
#include "make_widget.np.hxx"
#include "widget.np.hxx"

namespace Poly::Message {

struct Text : Widget {
  static constexpr NanoPack::TypeId TYPE_ID = 3495336243;

  std::string content;
  FontStyle style;

  Text() = default;

  Text(std::optional<int32_t> tag, std::string content, FontStyle style);

  Text(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  Text(const NanoPack::Reader &reader, int &bytes_read);

  size_t write_to(std::vector<uint8_t> &buf, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] int header_size() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;
};

} // namespace Poly::Message

#endif
