// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef UPDATE_WIDGET_NP_HXX
#define UPDATE_WIDGET_NP_HXX

#include <nanopack/message.hxx>
#include <nanopack/reader.hxx>
#include <vector>

#include "widget.np.hxx"

struct UpdateWidget : NanoPack::Message {
  static constexpr int32_t TYPE_ID = 3;

  int32_t tag;
  Widget widget;

  UpdateWidget() = default;

  UpdateWidget(int32_t tag, Widget widget);

  UpdateWidget(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  UpdateWidget(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] int32_t type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;
};

#endif
