// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "widget.np.hxx"

Poly::Message::Widget::Widget(std::optional<int32_t> tag)
    : tag(std::move(tag)) {}

Poly::Message::Widget::Widget(const NanoPack::Reader &reader, int &bytes_read) {
  const auto begin = reader.begin();
  int ptr = 8;

  if (reader.read_field_size(0) < 0) {
    this->tag = std::nullopt;
  } else {
    const int32_t tag = reader.read_int32(ptr);
    ptr += 4;
    this->tag = tag;
  }

  bytes_read = ptr;
}

Poly::Message::Widget::Widget(std::vector<uint8_t>::const_iterator begin,
                              int &bytes_read)
    : Widget(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId Poly::Message::Widget::type_id() const { return TYPE_ID; }

int Poly::Message::Widget::header_size() const { return 8; }

size_t Poly::Message::Widget::write_to(std::vector<uint8_t> &buf,
                                       int offset) const {
  size_t bytes_written = 8;

  buf.resize(offset + 8);

  NanoPack::write_type_id(TYPE_ID, offset, buf);

  if (tag.has_value()) {
    const auto tag = this->tag.value();
    NanoPack::write_field_size(0, 4, offset, buf);
    NanoPack::append_int32(tag, buf);
    bytes_written += 4;
  } else {
    NanoPack::write_field_size(0, -1, offset, buf);
  }

  return bytes_written;
}

std::vector<uint8_t> Poly::Message::Widget::data() const {
  std::vector<uint8_t> buf(8);
  write_to(buf, 0);
  return buf;
}
