// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "widget.np.hxx"

Poly::Message::Widget::Widget(std::optional<int32_t> tag)
    : tag(std::move(tag)) {}

Poly::Message::Widget::Widget(const NanoPack::Reader &reader, int &bytes_read) {
  const auto begin = reader.begin();
  int ptr = 8;

  if (reader.read_field_size(0) < 0) {
    this->tag = std::nullopt;
  } else {
    const int32_t tag = reader.read_int32(ptr);
    ptr += 4;
    this->tag = tag;
  }

  bytes_read = ptr;
}

Poly::Message::Widget::Widget(std::vector<uint8_t>::const_iterator begin,
                              int &bytes_read)
    : Widget(NanoPack::Reader(begin), bytes_read) {}

int32_t Poly::Message::Widget::type_id() const { return TYPE_ID; }

std::vector<uint8_t> Poly::Message::Widget::data() const {
  std::vector<uint8_t> buf(8);
  NanoPack::Writer writer(&buf);

  writer.write_type_id(TYPE_ID);

  if (tag.has_value()) {
    const auto tag = this->tag.value();
    writer.write_field_size(0, 4);
    writer.append_int32(tag);
  } else {
    writer.write_field_size(0, -1);
  }

  return buf;
}
