// AUTOMATICALLY GENERATED BY NANOC

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "click_event.np.hxx"

Rpc::ClickEvent::ClickEvent(uint32_t timestamp) : timestamp(timestamp) {}

size_t Rpc::ClickEvent::read_from(NanoPack::Reader &reader) {
  uint8_t *buf = reader.buffer;
  int ptr = 8;

  reader.read_uint32(ptr, timestamp);
  ptr += 4;

  return ptr;
}

NanoPack::TypeId Rpc::ClickEvent::type_id() const { return TYPE_ID; }

size_t Rpc::ClickEvent::header_size() const { return 8; }

size_t Rpc::ClickEvent::write_to(NanoPack::Writer &writer, int offset) const {
  const size_t writer_size_before = writer.size();

  writer.reserve_header(8);

  writer.write_type_id(TYPE_ID, offset);

  writer.write_field_size(0, 4, offset);
  writer.append_uint32(timestamp);

  return writer.size() - writer_size_before;
}
