// AUTOMATICALLY GENERATED BY NANOC

#ifndef CLICK_EVENT_NP_HXX
#define CLICK_EVENT_NP_HXX
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>

namespace Rpc {

struct ClickEvent : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 837166865;

  uint32_t timestamp;

  ClickEvent() = default;

  explicit ClickEvent(uint32_t timestamp);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

} // namespace Rpc

#endif
