// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "button.np.hxx"

Poly::Message::Button::Button(std::optional<int32_t> tag, std::string text,
                              int32_t on_click)
    : Widget(tag), text(std::move(text)), on_click(on_click) {}

Poly::Message::Button::Button(const NanoPack::Reader &reader, int &bytes_read)
    : Widget() {
  const auto begin = reader.begin();
  int ptr = 16;

  if (reader.read_field_size(0) < 0) {
    this->tag = std::nullopt;
  } else {
    const int32_t tag = reader.read_int32(ptr);
    ptr += 4;
    this->tag = tag;
  }

  const int32_t text_size = reader.read_field_size(1);
  text = reader.read_string(ptr, text_size);
  ptr += text_size;

  const int32_t on_click = reader.read_int32(ptr);
  ptr += 4;
  this->on_click = on_click;

  bytes_read = ptr;
}

Poly::Message::Button::Button(std::vector<uint8_t>::const_iterator begin,
                              int &bytes_read)
    : Button(NanoPack::Reader(begin), bytes_read) {}

int32_t Poly::Message::Button::type_id() const { return TYPE_ID; }

std::vector<uint8_t> Poly::Message::Button::data() const {
  std::vector<uint8_t> buf(16);
  NanoPack::Writer writer(&buf);

  writer.write_type_id(TYPE_ID);

  if (tag.has_value()) {
    const auto tag = this->tag.value();
    writer.write_field_size(0, 4);
    writer.append_int32(tag);
  } else {
    writer.write_field_size(0, -1);
  }

  writer.write_field_size(1, text.size());
  writer.append_string(text);

  writer.write_field_size(2, 4);
  writer.append_int32(on_click);

  return buf;
}

std::vector<uint8_t> Poly::Message::Button::data_with_length_prefix() const {
  std::vector<uint8_t> buf(16 + 4);
  NanoPack::Writer writer(&buf, 4);

  writer.write_type_id(TYPE_ID);

  if (tag.has_value()) {
    const auto tag = this->tag.value();
    writer.write_field_size(0, 4);
    writer.append_int32(tag);
  } else {
    writer.write_field_size(0, -1);
  }

  writer.write_field_size(1, text.size());
  writer.append_string(text);

  writer.write_field_size(2, 4);
  writer.append_int32(on_click);

  const size_t byte_size = buf.size() - 4;
  buf[0] = byte_size & 0xFF;
  buf[1] = byte_size & 0xFF00;
  buf[2] = byte_size & 0xFF0000;
  buf[3] = byte_size & 0xFF000000;

  return buf;
}
