// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef BUTTON_NP_HXX
#define BUTTON_NP_HXX

#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <string>
#include <vector>

#include "../make_widget.np.hxx"
#include "../widget.np.hxx"

namespace Poly::Message {

struct Button : Widget {
  static constexpr NanoPack::TypeId TYPE_ID = 320412644;

  std::string text;
  int32_t on_click;

  Button() = default;

  Button(std::optional<int32_t> tag, std::string text, int32_t on_click);

  Button(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  Button(const NanoPack::Reader &reader, int &bytes_read);

  size_t write_to(std::vector<uint8_t> &buf, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] int header_size() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;
};

} // namespace Poly::Message

#endif
