// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef BUTTON_NP_HXX
#define BUTTON_NP_HXX

#include <nanopack/reader.hxx>
#include <string>
#include <vector>

#include "../make_widget.np.hxx"
#include "../widget.np.hxx"

namespace Poly::Message {

struct Button : Widget {
  static constexpr int32_t TYPE_ID = 104;

  std::string text;
  int32_t on_click;

  Button() = default;

  Button(std::optional<int32_t> tag, std::string text, int32_t on_click);

  Button(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  Button(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] int32_t type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;

  [[nodiscard]] std::vector<uint8_t> data_with_length_prefix() const override;
};

} // namespace Poly::Message

#endif
